name: '💡 Idea Request'
description: 'Suggest a new idea, feature, or improvement for ParteeLabs projects'
title: '[IDEA] '
labels: ['idea', 'enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your idea! 🚀

        Please provide as much detail as possible to help us understand your suggestion.

  - type: textarea
    id: idea-description
    attributes:
      label: '💡 Idea Description'
      description: 'Describe your idea in detail. What problem does it solve or what improvement does it bring?'
      placeholder: 'Tell us about your idea...'
    validations:
      required: true

  - type: dropdown
    id: idea-category
    attributes:
      label: '📂 Category'
      description: 'What category does this idea fall under?'
      options:
        - 'New Product/Service'
        - 'Existing Product Enhancement'
        - 'Developer Experience'
        - 'Community Initiative'
        - 'Documentation'
        - 'Other'
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: '🎯 Problem Statement'
      description: 'What problem or pain point does this idea address?'
      placeholder: 'Describe the problem this idea would solve...'
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: '💭 Proposed Solution'
      description: 'How would you like to see this idea implemented?'
      placeholder: 'Describe your proposed solution...'
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: '✨ Expected Benefits'
      description: 'What benefits would this idea bring to the community?'
      placeholder: 'List the expected benefits...'
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: '⚡ Priority Level'
      description: 'How important do you think this idea is?'
      options:
        - 'Low - Nice to have'
        - 'Medium - Would be helpful'
        - 'High - Important for community'
        - 'Critical - Essential for success'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: '📋 Additional Context'
      description: 'Add any other context, examples, or references that might be helpful'
      placeholder: 'Any additional information, links, or examples...'
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: '📝 Submission Checklist'
      description: 'Please confirm the following:'
      options:
        - label: 'I have searched existing issues to avoid duplicates'
          required: true
        - label: 'I have read and agree to follow the Code of Conduct'
          required: true
        - label: 'I understand that this is a community-driven initiative'
          required: true
